apiVersion: apps/v1
kind: Deployment
metadata:
  name: raw-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raw-consumer
  template:
    metadata:
      labels:
        app: raw-consumer
    spec:
      containers:
      - name: raw-consumer
        image: raw-consumer:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"